### ISSUE TITLE
Blobstore access denied

### ISSUE THREAD

**Issue by mrosecrance** [martyca/minecraft-boshrelease#1]
Trying to create a release in this repository results in a  404:access denied when trying to pull down blobs. There is documentation on what bucket permissions need to look like here: https://bosh.io/docs/s3-release-blobstore/

Bosh.io is polling this repository for new versions. If this repo is no longer being developed, I'm hoping to stop our pipelines from looking here.  

```
        "- Downloading blob 'c1220df4-33dc-4844-6e13-492f91a8c556' with digest string 'a450bb3be2ecec1c97994b449a3c1821a0430531':\n    Getting blob from inner blobstore:\n      Getting blob from inner blobstore:\n        AccessDenied: Access Denied\n\tstatus code: 403, request id: 8F203C00468A45B4, host id: Fg/UGuU94lFybqULg+DBj6mx3CbKL/YJfxv2kOBrcoKFrRgq4TwR3b0AaG3+qGbcMAJgG6VkkNU=\n- Downloading blob 'b92e0b09-8c1d-4278-7aca-3922c631a830' with digest string '63527c993d8a8fe4dc384925a4149c8d3f0c63ad':\n    Getting blob from inner blobstore:\n      Getting blob from inner blobstore:\n        AccessDenied: Access Denied\n\tstatus code: 403, request id: 0BC93709F1A9965F, host id: jWcspffCsAp7dNdFn4B7fgzbp5XJcmRKrf2660VeIkA1qvMFyaDu2KylP6weX4d9scrH0azwrSQ=\n- Downloading blob '74ab59e1-d11b-4ca4-46fb-163fbb2cf2e4' with digest string 'd14d93d986cdcebe0cd819bd8d06a35293b4cc94':\n    Getting blob from inner blobstore:\n      Getting blob from inner blobstore:\n        AccessDenied: Access Denied\n\tstatus code: 403, request id: D837612CA826111C, host id: dZWhu8P/PuSkVvN51qIConV8CTCgW7i6kCOMCkqhUeNty+ExGUFL4nQV5FOcxqUohdafXAvRlpw=",
```

**Comment by mrosecrance** [comment]
I'm going to go ahead and remove this release from the bosh-io update pipeline. If you do end up making changes to this release and want to put that release on bosh-io feel free to open a PR then.

**Comment by martyca** [comment]
Fair play.
My intentions are to fix this in the near future, my current situation unfortunately doesnt allow for any time for sideprojects.
Thanks for the heads up.
